{
 "title": "(OE) DT status",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DT",
    "query": "BR1,BR2,CT1,CT2,ET0,LS0,MA0,MR0,OB0,PR1,PR2,RR0,RT0,SS1,SS2,TT0"
   }
  ]
 },
 "panels": [
  {
   "title": "DT status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "multiplier = 1000000\n\nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_status\" and  r._field == \"unready\")\n  |> range($range)\n  |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n"
    },
    {
     "query": "multiplier = 1000000\n\nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_status\" and r._field == \"unknown\")\n  |> range($range)\n  |> drop(columns:[\"_measurement\",\"process\", \"tag\"])\n"
    },
    {
     "query": "multiplier = 1000000\n\nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_status\" and  r._field == \"total\")\n  |> range($range)\n  |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "DT status per DT type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "multiplier = 1000000\n\nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_status_detailed_type\" and r._field == \"unknown\" and (\"$DT\" == \"All\" or r.type =~ /^${DT:pipe}$/))\n  |> range($range)\n  |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n\n"
    },
    {
     "query": "multiplier = 1000000\n\nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_status_detailed_type\" and r._field == \"unready\" and (\"$DT\" == \"All\" or r.type =~ /^${DT:pipe}$/))\n  |> range($range)\n  |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n\n"
    }
   ]
  },
  {
   "title": "DT distribution",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_dist_dt_node_id_type\" and r._field == \"count_i\" )\n  |> range($range)\n  |> last()\n  |> drop(columns:[\"process\", \"tag\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"type\"], valueColumn: \"_value\")\n  \n"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_dist_host_dt_node_id\" and r._field == \"count_i\" )\n  |> range($range)\n  |> last()\n  |> drop(columns:[\"process\", \"tag\"])"
    }
   ]
  },
  {
   "title": "DT distribution total per type",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"dtquery_dt_dist_type_type\" and r._field == \"count_i\" )\n  |> range($range)\n  |> last()\n  |> drop(columns:[\"process\", \"tag\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\", \"type\"], valueColumn: \"_value\")\n\n\n"
    }
   ]
  }
 ]
}