{
 "title": "(OE) Internal Monitoring Health",
 "description": "(\"server single\")",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Telegraf Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS Memory, OS View",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"memory_rss\" and r.process_name == \"telegraf\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"cpu_usage\" and r.process_name == \"telegraf\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of File Handles",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"num_fds\" and r.process_name == \"telegraf\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Metrics Received in 5 minutes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_gather\" and r.input == \"influxdb_listener\" and r._field == \"metrics_gathered\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\", \"input\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Metrics Sent to InfluxDB in 5 mintues",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_write\" and r.output == \"influxdb\" and r._field == \"metrics_written\" and r.output == \"influxdb\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Metrics Dropped in 5 mintues",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_write\" and r.output == \"influxdb\" and r._field == \"metrics_dropped\" and r.output == \"influxdb\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Maximum Time to Gather Metrics",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_gather\" and r.input == \"influxdb\" and r._field == \"gather_time_ns\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\", \"input\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Time to Write Metrics to InfluxDB",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_write\" and r.output == \"influxdb\" and r._field == \"write_time_ns\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\", \"output\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_telegraf_internal_write\" and r._field == \"buffer_size\" and r.output == \"influxdb\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"tag\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS Memory, OS View",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r._field == \"memory_rss\" and r.process_name == \"influxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r._field == \"cpu_usage\" and r.process_name == \"influxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of File Handles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r._field == \"num_fds\" and r.process_name == \"influxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Measurements",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_influxdb_database\" and r._field == \"numMeasurements\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"database\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Series",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_influxdb_database\" and r._field == \"numSeries\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"database\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Disk Space",
     "type": "graph",
     "description": "Size of /opt/emc/caspian/fabric/agent/services/object/data/influxdb/",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and (r._field == \"used\" or r._field == \"free\") and r.host =~ /influxdb/ and r.path == \"/pv\")\n  |> range($range)\n  |> keep(columns: [\"_start\", \"_stop\", \"_time\", \"_value\", \"host\", \"_field\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Points Written per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_main\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_influxdb_httpd\" and r._field == \"pointsWrittenOK\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:1s)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO rate (bytes per second)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r._field == \"read_bytes\" and r.process_name == \"influxd\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:1s)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"_field\"])\n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r._field == \"write_bytes\" and r.process_name == \"influxd\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:1s)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"_field\"])\n"
      }
     ]
    },
    {
     "title": "SQL Queries Executed in 5 minutes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_influxdb_queryExecutor\" and r._field == \"queriesExecuted\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Data Ingest Rate over HTTP, bytes per second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_main\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_influxdb_httpd\" and r._field == \"writeReqBytes\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n\n\n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Fluxd Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS Memory, OS View",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"memory_rss\" and r.process_name == \"fluxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"cpu_usage\" and r.process_name == \"fluxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of File Handles",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"num_fds\" and r.process_name == \"fluxd\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Requests in 5 minutes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_http_api_requests_total\" and r.path =~ /query/)\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"address\", \"status\", \"path\"])\n  |> derivative(nonNegative: true, unit:5m)\n  |> drop(columns: [\"path\"])\n  |> window(every:5m)\n  |> sum()\n  |> rename(columns: {_start: \"_time\"})\n  |> group(columns:[\"address\", \"status\"])\n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time by result",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "sum = from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_http_api_request_duration_seconds\" and r._field == \"sum\" and r.path == \"/query\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"address\", \"status\", \"_value\"])\n  \ncount = from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_http_api_request_duration_seconds\" and r._field == \"count\" and r.path == \"/query\")\n  |> range($range)\n  |> derivative(nonNegative: true, unit:5m)\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"address\", \"status\", \"_value\"])\n\njoin(tables: {sum:sum, count:count}, on: [\"_time\", \"_start\", \"_stop\", \"address\", \"status\"])\r\n  |> map(fn: (r) => ({_value: r._value_sum / r._value_count, _time: r._time}))\n  ",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of connected InfluxDB",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "        \nfrom(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_host_state\")\n  |> range($range)\n  |> group(columns: [\"_time\",\"address\"], mode:\"by\")\n  |> sum()\n  |> group(columns: [\"address\"], mode:\"by\")\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Disconnects",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_host_state_change_total\" and r.status ==\"DISCONNECTED\")\n  |> range($range)\n  |> keep(columns: [\"_time\",\"_start\", \"_stop\",\"_value\", \"address\",\"hostport\"])\n  |> difference()\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  \n  \n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of InfluxDB Selections in 5 Minutes",
     "type": "graph",
     "description": "- Number of single InfluxDB selections in 5 minutes\n- Number of failed selections caused by expired host selection data",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\n\r|> filter(fn: (r) => r._measurement == \"tsdb_fluxd_host_selected\" and r._field == \"counter\")\r\n\r|> range($range)\n\r|> keep(columns: [\"_time\", \"_value\", \"address\", \"hostport\"])\r\n\r|> difference(nonNegative: true)\r\n\r|> fill(column: \"_value\", value: 0)\r\n\r|> drop(columns: [\"hostport\"])\r\n|> window(every:5m)\n|> sum()\r\n|> rename(columns: {_start: \"_time\"})\r\n|> group(columns: [\"address\"])\n\r\r|> set(key: \"_field\", value: \"Successful\")\n\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "query": "from(bucket: \"monitoring_op\")\n\r|> filter(fn: (r) => r._measurement == \"tsdb_fluxd_hl_expired_detected\" and r._field == \"counter\" and r.host =~ /${host:pipe}/)\r\n\r|> range($range)\n\r|> keep(columns: [\"_time\", \"_value\", \"address\"])\r\n\r|> difference(nonNegative: true)\r\n\r|> fill(column: \"_value\", value: 0)\r\n\r\r|> set(key: \"_field\", value: \"Failed due to expired data\")\n"
      }
     ]
    },
    {
     "title": "Number of Queries Executed in 5 minutes",
     "type": "graph",
     "description": "Number of queries executed on local Flux engine",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_query_control_executing_duration_seconds\" and r._field =~ /count/)\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"address\"])\n  |> derivative(nonNegative: true, unit:5m)\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Queries Forwarded in 5 minutes",
     "type": "graph",
     "description": "Number of queries forwarded and executed on remote Fluxd instances",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_http_lb_request_forwarded\" and r._field =~ /count/)\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"address\"])\n  |> derivative(nonNegative: true, unit:5m)",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Flux Internal Errors",
     "type": "graph",
     "description": "Total number of internal fluxd errors (internal panics counter)",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\") \n   |> filter(fn: (r) => r._measurement == \"tsdb_fluxd_query_control_panics_total\" and r._field == \"counter\")\n   |> range($range)\n   |> keep(columns: [\"_time\", \"_value\", \"address\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "Throttler and Grafana instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSS Memory, OS View",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"memory_rss\" and (r.process_name == \"throttler\" or r.process_name == \"grafana-server\"))\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"process_name\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"cpu_usage\" and (r.process_name == \"throttler\" or r.process_name == \"grafana-server\"))\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"process_name\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of File Handles",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"procstat\" and r.host =~ /${host:pipe}/ and r._field == \"num_fds\" and (r.process_name == \"throttler\" or r.process_name == \"grafana-server\"))\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"process_name\"])",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total CQ processing rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_fluxd_requests_total\")\n  |> range($range)\n  |> difference(nonNegative:true)\n  |> keep(columns: [\"_time\", \"_value\", \"type\", \"host\", \"status\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CQ Telegraf requests rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_telegraf_requests_total\")\n  |> range($range)\n  |> difference(nonNegative:true)\n  |> keep(columns: [\"_time\", \"_value\", \"type\", \"host\", \"status\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CQ progress done status by name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_vdc\")\r\n  |> filter(fn: (r) => r._measurement =~ /^cq_.*_metadata$/ and r._field == \"_done\")\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of successfully processed \"current\" CQ by name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_succeeded_cq_total\" and r.type == \"current\")\n  |> range($range)\n  |> difference(nonNegative:true)\n  |> keep(columns: [\"_time\", \"_value\", \"cqname\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of successfully processed \"history\" CQ by name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_succeeded_cq_total\" and r.type == \"history\")\n  |> range($range)\n  |> difference(nonNegative:true)\n  |> keep(columns: [\"_time\", \"_value\", \"cqname\", \"type\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of CQ exceeded max-retry count per 5 min, per query",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_exceeded_maxretry_total\")\n  |> range($range)\n  |> keep(columns: [\"_time\",\"_value\", \"host\", \"cqname\"]) \n  |> derivative(nonNegative: true, unit: 5m)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  \n  \n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CQ number of bad requests to Fluxd",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_fluxd_requests_total\" and r.status!=\"ok\")\n  |> range($range)\n  |> difference()\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"status\", \"type\"])\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of CQ exceeded max-retry count per 5 min",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_exceeded_maxretry_common_total\")\n  |> range($range)\n  |> keep(columns: [\"_time\",\"_value\", \"host\"])\n  |> derivative(nonNegative: true, unit: 5m)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  \n  \n  \n  \n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CQ number of  non completed history processing",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"cquerier_non_completed_history_cq_total\")\n  |> range($range)\n  |> difference(nonNegative:true)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Statclient meta-monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Primitives per Service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement =~ /_stat_client_performance$/ and r._field == \"primitives_count\" and r.host =~ /${host:pipe}/)\n  |> range($range)\n  |> drop(columns: [\"_measurement\", \"_field\", \"node_id\", \"tag\", \"host\", \"_start\", \"_stop\"])\n\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Exported Points (lines) per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement =~ /_stat_client_performance$/ and r._field == \"exported_points\" and r.host =~ /${host:pipe}/)\n  |> range($range)\n  |> drop(columns: [\"_measurement\", \"_field\", \"node_id\", \"tag\", \"host\", \"_start\", \"_stop\"])\n  |> derivative(nonNegative: true)\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Events of InfluxDB buffer loss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement =~ /_stat_client_performance$/ and r._field == \"influxdb_buffer_loss\" and r.host =~ /${host:pipe}/)\n  |> range($range)\n  |> drop(columns: [\"_measurement\", \"_field\", \"node_id\", \"tag\", \"host\", \"_start\", \"_stop\"])\n  |> difference(nonNegative:true)\n\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Maximum Push Interval in seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "space: free, $tag_path",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement =~ /_stat_client_performance$/ and r._field == \"push_interval_sec\" and r.host =~ /${host:pipe}/)\n  |> range($range)\n  |> keep(columns: [\"_time\", \"_value\", \"process\"])\n",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}