{
 "title": "Capacity - Overview by Nodes",
 "tags": [ "Capacity" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "label": "Node",
    "query": "from(bucket:\"monitoring_main\")|> range(start: -12h)|> filter(fn:(r) => r._measurement == \"ssm_sstable_SSTable_SS\" and r._field != \"state\")|> drop(columns: [\"_value\"])|> group(columns:[\"SS\"])|> distinct(column:\"SS\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Trend",
   "type": "table",
   "description": "The forecast table provides an estimated number of days when the node capacity is expected to reach 50% and 80% based on the last 1, 7, and 30 days trend.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "sec_in_ns = 1000000000\nalign_time = 15 * 60\nstop_time_aligned = $__range_to_s / align_time * align_time\nstop_dt = time(v:stop_time_aligned * sec_in_ns)\n\ntotal = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\" and r._field == \"total_i\")\n|> range(start: -24h)\n|> last()\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"_host_id\"])\n|> rename(columns: {_host_id: \"host_id\"})\n|> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n|> drop(columns: [\"_time\"])\n//|> yield(name: \"nodes\")\n\ntarget50 = total\n|> map(fn: (r) => ({ total: int(v: float(v: r.total_i) * 0.5) }))\n\ntarget80 = total\n|> map(fn: (r) => ({ total: int(v: float(v: r.total_i) * 0.8) }))\n//|> yield(name: \"target80\")\n\nused30Days = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\" and r._field == \"used\")\n|> range(start: -30d)\n|> keep(columns: [\"_time\", \"_value\", \"_host_id\", \"_field\"])\n|> rename(columns: {_host_id: \"host_id\"})\n|> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n//|> yield(name: \"used30\")\n\nused7Days = used30Days\n|> range(start: -7d)\n\nused1Day = used7Days\n|> range(start: -1d)\n//|> yield(name: \"used1d\")\n\ndays1Target50 = join(tables: {t: target50, u: used1Day}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t1_D1T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t1_D1T50\")\n\ndays7Target50 = join(tables: {t: target50, u: used7Days}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t2_D7T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t2_D7T50\")\n\ndays30Target50 = join(tables: {t: target50, u: used30Days}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t3_D30T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t3_D30T50\")\n\ndays1Target80 = join(tables: {t: target80, u: used1Day}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t4_D1T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t4_D1T80\")\n\ndays7Target80 = join(tables: {t: target80, u: used7Days}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t5_D7T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t5_D7T80\")\n\ndays30Target80 = join(tables: {t: target80, u: used30Days}, on: [\"host_id\"])\n|> map(fn: (r) => ({_time: r._time, _value: r.used - r.total}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({t6_D30T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else (if r._value > 0.0 then string(v: 0.0) else \"N/A\")}))\n|> yield(name: \"t6_D30T80\")\n"
    }
   ]
  },
  {
   "type": "table",
   "description": "Monitor the total, used, and available capacity by ObjectStore nodes.\nReserved capacity is the 10 percent of the total capacity that is reserved for failure handling and performing erasure encoding/XOR operations.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n  |> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\"\n                       and (r._field == \"total_i\" or r._field == \"used\"\n                            or r._field == \"available\" or r._field == \"reserved\"\n                            or r._field == \"offline\" or r._field == \"used\"))\n  |> range(start: -1h)\n  |> last()\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"_host_id\"])\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n  |> map(fn: (r) => ({\"vl0_Node\": r._host_id, \"vl1_Total\": r.total_i, \"vl2_Used\": r.used, \"vl3_Available\": r.available, \"vl4_Reserved\": r.reserved, \"vl5_Offline\":  r.offline}))\n"
    }
   ]
  },
  {
   "title": "Capacity History by Node ($node_id)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\"\nand r._host_id == \"$node_id\"\nand r._field == \"total_i\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"_host_id\"])\n|> set(key: \"_field\", value: \"Total\")"
      }
     ]
    },
    {
     "title": "Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\"\nand r._host_id == \"$node_id\"\nand r._field == \"used\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"_host_id\"])\n|> set(key: \"_field\", value: \"Used\")\n"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_nodes\"\nand r._host_id == \"$node_id\"\nand r._field == \"available\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"_host_id\"])\n|> set(key: \"_field\", value: \"Available\")\n"
      }
     ]
    }
   ]
  }
 ]
}