{
 "title": "Capacity - Overview",
 "tags": [ "Capacity" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Trends",
   "type": "table",
   "description": "The forecast table provides an estimated number of days when the capacity is expected to reach 50% and 80% based on the last 1, 7, and 30 days trend.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "sec_in_ns = 1000000000\nalign_time = 15 * 60\nstop_time_aligned = $__range_to_s / align_time * align_time\nstop_dt = time(v:stop_time_aligned * sec_in_ns)\n\ntotal = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\" and r._field == \"total_i\")\n|> range(start: -24h)\n|> last()\n|> toFloat()\n|> keep(columns: [\"_value\"])\n\ntarget50 = total\n|> map(fn: (r) => ({_value: int(v: r._value * 0.5) }))\n\ntarget80 = total\n|> map(fn: (r) => ({_value: int(v: r._value * 0.8) }))\n\nused30Days = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\" and r._field == \"used\")\n|> range(start: -30d)\n|> keep(columns: [\"_time\", \"_value\"]) \n\nused7Days = used30Days \n|> range(start: -7d) \n\nused1Day = used7Days \n|> range(start: -1d) \n\ndays30Target50 = join(tables: {t: target50, u: used30Days}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T3_D30T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T3_D30T50\")\n\ndays30Target80 = join(tables: {t: target80, u: used30Days}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T6_D30T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T6_D30T80\")\n\ndays7Target50 = join(tables: {t: target50, u: used7Days}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T2_D7T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T2_D7T50\")\n\ndays7Target80 = join(tables: {t: target80, u: used7Days}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T5_D7T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T5_D7T80\")\n\ndays1Target50 = join(tables: {t: target50, u: used1Day}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T1_D1T50: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T1_D1T50\")\n\ndays1Target80 = join(tables: {t: target80, u: used1Day}, on: [\"\"])\n|> map(fn: (r) => ({_time: r._time, _value: r._value_u - r._value_t}))\n|> predictLinear(wantedValue: 0.0)\n|> map(fn: (r) => ({T4_D1T80: if r._time > now() then string(v: (int(v: r._time) - int(v:stop_dt)) / sec_in_ns) else \"N/A\"}))\n|> yield(name: \"T4_D1T80\")\n"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "table",
   "description": "Monitor the total, used, and available capacity at the ObjectStore level.\nReserved capacity is the 10 percent of the total capacity that is reserved for failure handling and performing erasure encoding/XOR operations.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n  |> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"\n                       and (r._field == \"total_i\" or r._field == \"used\"\n                            or r._field == \"available\" or r._field == \"reserved\"\n                            or r._field == \"offline\"))\n  |> range(start: -1h)\n  |> last()\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n  |> map(fn: (r) => ({\"vl0_Total\": r.total_i, \"vl1_Used\": r.used, \"vl2_Available\": r.available, \"vl3_Reserved\": r.reserved}))\n"
    }
   ]
  },
  {
   "title": "Capacity History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "graph",
     "description": "History of the total ObjectStore capacity.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\" and r._field == \"total_i\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Total\")"
      }
     ]
    },
    {
     "title": "Used",
     "type": "graph",
     "description": "History of the used ObjectStore capacity.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"and r._field == \"used\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Used\")\n"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "description": "History of the available ObjectStore capacity.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"and r._field == \"available\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Available\")\n"
      }
     ]
    }
   ]
  }
 ]
}