{
 "title": "Capacity - by Nodes",
 "tags": [ "Capacity" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": "from(bucket:\"monitoring_main\")|> range(start: -12h)|> filter(fn:(r) => r._measurement == \"ssm_sstable_SSTable_SS\" and r._field != \"state\")|> drop(columns: [\"_value\"])|> group(columns:[\"SS\"])|> distinct(column:\"SS\")"
   },
   {
    "name": "pd",
    "label": "Partition Uid",
    "query": "from(bucket:\"monitoring_main\") |> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD_status\" and r.SS == \"$node_id\") |> range(start: -12h) |> keep(columns: [\"PD\"]) |> distinct(column: \"PD\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "import \"math\"\n\ndiskStatusOK = from(bucket: \"monitoring_main\")\n// Show only not MISSING and not REMOVED disksdiskStatusOK = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD_status\" and r._field == \"hwState\" and r.SS == \"$node_id\")\n|> range(start: -12h)\n|> last()\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"SSTable\", \"SS\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")// drop 'SSTable' to get the latest value per PD after sorting by '_time'\n|> keep(columns: [\"PD\", \"SS\", \"hwState\", \"hwState\",, \"_time\"])\n|> rename(columns:{hwState: \"_value\"})\n|> sort(columns: [\"_time\"])\n|> last()\n|> filter(fn: (r) => r._value != \"MISSING\" and r._value != \"REMOVED\")\n|> keep(columns: [\"SS\", \"PD\"])\n\ntotalSpace = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\"\n              and r._field == \"totalSpace\" and r.SS == \"$node_id\")\n|> range(start: -12h)\n|> last()\n|> keep(columns: [\"_time\", \"_stop\", \"_field\", \"_value\", \"SSTable\", \"SS\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{totalSpace: \"_value\"})\n|> sort(columns: [\"_time\"])\n|> last()\n|> keep(columns: [\"PD\", \"SS\", \"SSTable\", \"_value\", \"_stop\"])\n|> rename(columns: {_stop: \"_time\"})\n\ntotalSpaceOK = join(tables: {totalSpace: totalSpace, diskStatusOK: diskStatusOK}, on: [\"SS\", \"PD\"])\n\nfreeSpace = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\"\n              and r._field == \"freeSpace\" and r.SS == \"$node_id\")\n|> range(start: -12h)\n|> last()\n|> keep(columns: [\"_time\", \"_stop\", \"_field\", \"_value\", \"SSTable\", \"SS\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{freeSpace: \"_value\"})\n|> sort(columns: [\"_time\"])\n|> last()\n|> keep(columns: [\"PD\", \"SS\", \"SSTable\", \"_value\", \"_stop\"])\n|> rename(columns: {_stop: \"_time\"})\n\nfreeSpaceOK = join(tables: {freeSpace: freeSpace, diskStatusOK: diskStatusOK}, on: [\"SS\", \"PD\"])\n\n\n// used = (total - free) for each SSTable/PD/SS\n// BAD disk freeSpace value may be greater than totalSpace value, show 0 in this caseused = join(tables: {totalSpace: totalSpaceOK, freeSpace: freeSpaceOK}, on: [\"SSTable\", \"SS\", \"PD\"])\nused = join(tables: {totalSpace: totalSpaceOK, freeSpace: freeSpaceOK}, on: [\"SSTable\", \"SS\", \"PD\"])\n|> rename(columns: {_time_freeSpace: \"_time\"})\n|> keep(columns: [\"_time\", \"_value_freeSpace\", \"_value_totalSpace\", \"PD\", \"SS\", \"SSTable\"])\n|> map(fn: (r) => ({_value: int(v: math.mMax(x: float(v: r._value_totalSpace - r._value_freeSpace), y: float(v: 0)))}))\n|> keep(columns: [\"_time\", \"_value\", \"PD\", \"SS\"])\n|> sum()\n|> set(key: \"_field\",value: \"used\")\n\navailable = freeSpaceOK\n|> keep(columns: [\"_time\", \"_value\", \"PD\", \"SS\"])\n|> sum()\n|> set(key: \"_field\",value: \"available\")\n\ntotal = totalSpaceOK\n|> keep(columns: [\"_time\", \"_value\", \"PD\", \"SS\"])\n|> sum()\n|> set(key: \"_field\",value: \"total\")\n\nunion(tables: [available, total, used])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> keep(columns: [\"PD\", \"used\", \"available\", \"total\"])\n|> group()\n|> map(fn: (r) => ({\n\"vl0_Partition\": r.PD,\n\"vl1_Total\": r.total,\n\"vl2_Used\": r.used,\n\"vl3_Available\": r.available,\n})"
    }
   ]
  },
  {
   "title": "Capacity History by Disk ($pd)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "// stale_update_period = 6 hours\nstale_update_period_s = 21600\nextended_range_start = int(v:$__range_from_s) - stale_update_period_s\nextended_range_stop = int(v:$__range_to_s)\n\nfrom(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\" and r._field == \"totalSpace\"and r.PD == \"$pd\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> fillMissing(period: 5m)\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"SSTable\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{totalSpace: \"_value\"})\n|> window(every: 60m)\n|> sort(columns: [\"_time\"])\n|> last()\n|> drop(columns: [\"SSTable\"])\n|> sum()\n|> rename(columns:{_stop: \"_time\"})\n|> group()\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"PD\"])\n|> set(key: \"_field\", value: \"Total\")\n"
      }
     ]
    },
    {
     "title": "Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "import \"math\"\nstale_update_period_s = 21600\nextended_range_start = int(v:$__range_from_s) - stale_update_period_s\nextended_range_stop = int(v:$__range_to_s)\n\ntotalSpace = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\" and r._field == \"totalSpace\" and r.PD == \"$pd\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> fillMissing(period: 5m)\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"SSTable\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{totalSpace: \"_value\"})\n|> window(every: 60m)\n|> sort(columns: [\"_time\"])\n|> last()\n|> drop(columns: [\"SSTable\"])\n|> sum()\n|> rename(columns:{_stop: \"_time\"})\n|> keep(columns: [\"_time\", \"_value\", \"PD\"])\n\nfreeSpace = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\" and r._field == \"freeSpace\" and r.PD == \"$pd\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> fillMissing(period: 5m)\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"SSTable\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{freeSpace: \"_value\"})\n|> window(every: 60m)\n|> sort(columns: [\"_time\"])\n|> last()\n|> drop(columns: [\"SSTable\"])\n|> sum()\n|> rename(columns:{_stop: \"_time\"})\n|> keep(columns: [\"_time\", \"_value\", \"PD\"])\n\n// used = (total - free)\n// BAD disk freeSpace value may be greater than totalSpace value, show 0 in this case\njoin(tables: {totalSpace: totalSpace, freeSpace: freeSpace}, on: [\"_time\", \"PD\"])\n|> map(fn: (r) => ({_value: int(v: math.mMax(x: float(v: r._value_totalSpace - r._value_freeSpace), y: float(v: 0)))}))\n|> group()\n|> range($range)\n|> set(key: \"_field\", value: \"Used\")"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "// stale_update_period = 6 hours\nstale_update_period_s = 21600\nextended_range_start = int(v:$__range_from_s) - stale_update_period_s\nextended_range_stop = int(v:$__range_to_s)\n\nfrom(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"ssm_sstable_SSTable_SS_partitions_PD\" and r._field == \"freeSpace\" and r.PD == \"$pd\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> fillMissing(period: 5m)\n|> keep(columns: [\"_time\", \"_field\", \"_value\", \"SSTable\", \"PD\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> rename(columns:{freeSpace: \"_value\"})\n|> window(every: 60m)\n|> sort(columns: [\"_time\"])\n|> last()\n|> drop(columns: [\"SSTable\"])\n|> sum()\n|> rename(columns:{_stop: \"_time\"})\n|> group()\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"PD\"])\n|> set(key: \"_field\", value: \"Available\")\n"
      }
     ]
    }
   ]
  }
 ]
}