{
 "title": "Capacity Utilization: CAS Processing",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "from(bucket:\"monitoring_vdc\")     |> range(start: -1h)     |> filter(fn:(r) => r._measurement == \"cq_capacity_cas_gc_blob\")     |> group(columns:[\"BUCKET\"])     |> distinct(column:\"BUCKET\")"
   },
   {
    "name": "bucket",
    "query": "from(bucket:\"monitoring_vdc\")     |> range(start: -1h)     |> filter(fn:(r) => r._measurement == \"cq_capacity_cas_gc_blob\" and r.BUCKET =~ /$namespace/)     |> group(columns:[\"BUCKET\"])     |> distinct(column:\"BUCKET\")"
   }
  ]
 },
 "panels": [
  {
   "title": "CAS Processing",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_blob\")\r\n|> range($range)\r\n|> last()\n|> drop(columns:[\"_measurement\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> drop(columns:[\"_time\"])\n|> rename(columns:{data_detected: \"blobSize\", objects_detected: \"blobCount\"})\r"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_reflection\")\r\n|> range($range)\r\n|> last()\n|> drop(columns:[\"_measurement\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> drop(columns:[\"_time\"])\n|> rename(columns:{data_detected: \"reflectionSize\", objects_detected: \"reflectionCount\"})\r\n"
    }
   ]
  },
  {
   "title": "History for bucket: $bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unreferenced Blob Data Detected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_blob\" and r._field == \"data_detected\" and r.BUCKET =~ /${namespace}.*${bucket}-/)\r\n|> range($range)\r\n|> drop(columns:[\"_measurement\", \"_field\", \"BUCKET\"])"
      }
     ]
    },
    {
     "title": "Unreferenced Blobs Detected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_blob\" and r._field == \"objects_detected\" and r.BUCKET =~ /${namespace}.*${bucket}-/)\r\n|> range($range)\r\n|> drop(columns:[\"_measurement\", \"_field\", \"BUCKET\"])"
      }
     ]
    },
    {
     "title": "Reflection Data Detected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_reflection\" and r._field == \"data_detected\" and r.BUCKET =~ /${namespace}.*${bucket}-/)\r\n|> range($range)\r\n|> drop(columns:[\"_measurement\", \"_field\", \"BUCKET\"])"
      }
     ]
    },
    {
     "title": "Reflections Expired",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_cas_gc_reflection\" and r._field == \"objects_detected\" and r.BUCKET =~ /${namespace}.*${bucket}-/)\r\n|> range($range)\r\n|> drop(columns:[\"_measurement\", \"_field\", \"BUCKET\"])"
      }
     ]
    }
   ]
  }
 ]
}