{
 "title": "Data Access Performance - by Protocols",
 "tags": [ "Data Access Performance" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "head", "label": "Protocol", "query": "ATMOS,CAS,HDFS,NFS,S3,SWIFT" }
  ]
 },
 "panels": [
  {
   "title": "Transaction Summary for $head",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// need this 'default' table to substitute possibly missing sys_errors table if errors were not registered by ECS service\nimport \"csv\"\ndefault_sys_errors = csv.from(csv:\"#datatype,string,long,string,long\n#group,false,false,true,false\n#default,_result,,,\n,result,table,_field,_value\n,,100,succeed_request_counter_i,0\n,,101,system_errors_i,0\n,,102,user_errors_i,0\")\n\ntotals = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_transaction_head_delta\" and r.head =~ /^${head:pipe}$/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nsys_errors = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_error_head_delta\" and r.head =~ /^${head:pipe}$/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nunion(tables: [default_sys_errors, totals, sys_errors])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")\n// map does not save non-group columns\n|> map(fn:(r) => ({\na_succeed_request_counter: r.succeed_request_counter_i,\nb_system_errors: r.system_errors_i,\nc_user_errors: r.user_errors_i,\nd_error_rate: float(v:r.system_errors_i+r.user_errors_i)/\nfloat(v:r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i\n// this trick is needed because failed+succeed can be 0, avoid printing NaN in this case\n+int(v:bool(v:(r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i)==0)))}))\n\n"
    }
   ]
  },
  {
   "title": "TPS (success/failure)",
   "type": "graph",
   "description": "Rate of successful requests and failures per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_transaction_head\" and r.head =~ /^${head:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Bandwidth (read/write)",
   "type": "graph",
   "description": "Data access bandwidth of successful requests per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_throughput_head\" and r.head =~ /^${head:pipe}$/)\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_field\", \"_value\"]) \n|> window(every:wl_dur)\n|> sum()\n|> group(columns:[\"_field\"])\n|> rename(columns: {_start: \"_time\"})\n\n"
    }
   ]
  },
  {
   "title": "Failed Requests/s by error type (user/system)",
   "type": "graph",
   "description": "Rate of failed requests per second, split by error type (user/system)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_error_head\" and r.head =~ /^${head:pipe}$/)\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_field\", \"_value\"]) \n|> window(every:wl_dur)\n|> sum()\n|> group(columns:[\"_field\"]) \n|> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency of read/write requests\nNote that if multiple protocols are selected, mean value is displayed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nall = from(bucket: \"monitoring_vdc\") \n    |> filter(fn: (r) => r._measurement =~ /^cq_performance_latency_head_*/ and r.head =~ /^${head:pipe}$/)  \n    |> range(start: start_dt, stop: end_dt)\n    |> window(every:wl_dur)\n    |> mean()\n    |> drop(columns:[\"head\"])    \n// TODO this is not exactly correct way of handling percentiles\n// However if only one protocol is selected, this \"mean\" won't change anything\n// In a better option, value should be recalculated from raw data if multiple protocols are selected\n    |> mean()\n    |> group(columns:[\"_field\",\"id\"])\n\n// can't simple rename ttfb_read to Read, ti... and similarly for ttlb_write\n// when they are in same stream\n// TODO think about possible optimizations:\n// 1. use function? didn't work at first approach, flux can't see it\n// 2. use join with another table created from CSV\n\nreads = all |> filter(fn: (r) => r.id == \"ttfb_read\" )\n    |> set(key: \"id\", value: \"Read, time to first byte\")\n\nwrites = all |> filter(fn: (r) => r.id == \"ttlb_write\" )\n    |> set(key: \"id\", value: \"Write, time to last byte\")\n\nunion(tables: [reads, writes])|> map(fn:(r) => ({_time: r._start, _value: r._value, _field: r.id + \", \" + r._field })) |>drop(columns:[\"id\"])\n\n\n    \n\n\n"
    }
   ]
  },
  {
   "title": "Requests drill down by nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Requests/s by Node",
     "type": "graph",
     "description": "Rate of successful requests per second, by node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head\" and r._field == \"succeed_request_counter\" and r.head =~ /^${head:pipe}$/ )\n\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"head\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"head\"])\n|> sum()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})\n\n"
      }
     ]
    },
    {
     "title": "Failed Requests/s by Node",
     "type": "graph",
     "description": "Rate of failed requests per second, split by node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head\" and r._field == \"failed_request_counter\" and r.head =~ /^${head:pipe}$/ )\n\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"head\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"head\"])\n|> sum()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Compare: select multiple protocols",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compare TPS of successful requests",
     "type": "graph",
     "description": "Select multiple protocols and compare rates of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n \n  \n  from(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_transaction_head\" and r._field == \"succeed_request_counter\" and r.head =~ /^${head:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_value\", \"head\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\",\"head\"]) \n  |> rename(columns: {_start: \"_time\", head: \"protocol\"})\n"
      }
     ]
    },
    {
     "title": "Compare rate of failed requests/s",
     "type": "graph",
     "description": "Select multiple protocols and compare rates of failed requests per second, split by error type (user/system)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n  \nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_error_head\" and r.head =~ /^${head:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"head\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\",\"head\"]) \n  |> rename(columns: {_start: \"_time\", head: \"protocol\"})"
      }
     ]
    },
    {
     "title": "Compare read bandwidth",
     "type": "graph",
     "description": "Select multiple protocols and compare data access bandwidth of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n  \n  from(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_throughput_head\" and r._field == \"total_read_requests_size\" and r.head =~ /^${head:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"head\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\",\"head\"]) \n  |> rename(columns: {_start: \"_time\", head: \"protocol\"})"
      }
     ]
    },
    {
     "title": "Compare write bandwidth",
     "type": "graph",
     "description": "Select multiple protocols and compare data access bandwidth of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n  \n  from(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_throughput_head\" and r._field == \"total_write_requests_size\" and r.head =~ /^${head:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"head\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\",\"head\"]) \n  |> rename(columns: {_start: \"_time\", head: \"protocol\"})"
      }
     ]
    },
    {
     "title": "Compare read latency",
     "type": "graph",
     "description": "Select multiple protocols and compare latency of read requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nall = from(bucket: \"monitoring_vdc\") \n    |> filter(fn: (r) => r._measurement =~ /^cq_performance_latency_head_*/ and r.id == \"ttfb_read\" and r.head =~ /^${head:pipe}$/)  \n    |> range(start: start_dt, stop: end_dt)\n    |> window(every:wl_dur)\n    |> mean()\n    |> group(columns:[\"_field\",\"id\",\"head\"])\n\n// can't simple rename ttfb_read to Read, ti... and similarly for ttlb_write\n// when they are in same stream\n// TODO think about possible optimizations:\n// 1. use function? didn't work at first approach, flux can't see it\n// 2. use join with another table created from CSV\n\nreads = all |> filter(fn: (r) => r.id == \"ttfb_read\" )\n    |> set(key: \"id\", value: \"Read, time to first byte\")\n\nwrites = all |> filter(fn: (r) => r.id == \"ttlb_write\" )\n    |> set(key: \"id\", value: \"Write, time to last byte\")\n\nunion(tables: [reads, writes])|> map(fn:(r) => ({_time: r._start, _value: r._value, _field: r.id + \", \" + r._field })) |>drop(columns:[\"id\"])\n"
      }
     ]
    },
    {
     "title": "Compare wrtie latency",
     "type": "graph",
     "description": "Select multiple protocols and compare latency of write requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nall = from(bucket: \"monitoring_vdc\") \n    |> filter(fn: (r) => r._measurement =~ /^cq_performance_latency_head_*/ and r.id == \"ttlb_write\" and r.head =~ /^${head:pipe}$/)  \n    |> range(start: start_dt, stop: end_dt)\n    |> window(every:wl_dur)\n    |> mean()\n    |> group(columns:[\"_field\",\"id\",\"head\"])\n\n// can't simple rename ttfb_read to Read, ti... and similarly for ttlb_write\n// when they are in same stream\n// TODO think about possible optimizations:\n// 1. use function? didn't work at first approach, flux can't see it\n// 2. use join with another table created from CSV\n\nreads = all |> filter(fn: (r) => r.id == \"ttfb_read\" )\n    |> set(key: \"id\", value: \"Read, time to first byte\")\n\nwrites = all |> filter(fn: (r) => r.id == \"ttlb_write\" )\n    |> set(key: \"id\", value: \"Write, time to last byte\")\n\nunion(tables: [reads, writes])|> map(fn:(r) => ({_time: r._start, _value: r._value, _field: r.id + \", \" + r._field })) |>drop(columns:[\"id\"])\n"
      }
     ]
    }
   ]
  }
 ]
}