{
 "title": "Data Access Performance - by Namespaces",
 "tags": [ "Data Access Performance" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "tag_values(monitoring_vdc, cq_performance_transaction_ns, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction Summary for selected namespaces",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// need this 'default' table to substitute possibly missing sys_errors table if errors were not registered by ECS service\nimport \"csv\"\ndefault_sys_errors = csv.from(csv:\"#datatype,string,long,string,long\n#group,false,false,true,false\n#default,_result,,,\n,result,table,_field,_value\n,,100,succeed_request_counter_i,0\n,,101,system_errors_i,0\n,,102,user_errors_i,0\")\n\ntotals = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_transaction_ns_delta\" and r.namespace =~ /^${namespace:pipe}$/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nsys_errors = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_error_ns_delta\" and r.namespace =~ /^${namespace:pipe}$/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nunion(tables: [default_sys_errors, totals, sys_errors])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")\n// map does not save non-group columns\n|> map(fn:(r) => ({\na_succeed_request_counter: r.succeed_request_counter_i,\nb_system_errors: r.system_errors_i,\nc_user_errors: r.user_errors_i,\nd_error_rate: float(v:r.system_errors_i+r.user_errors_i)/\nfloat(v:r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i\n// this trick is needed because failed+succeed can be 0, avoid printing NaN in this case\n+int(v:bool(v:(r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i)==0)))}))\n\n"
    }
   ]
  },
  {
   "title": "TPS (success/failure)",
   "type": "graph",
   "description": "Rate of successful requests and failures per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_transaction_ns\" and r.namespace =~ /^${namespace:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Failed Requests/s by error type (user/system)",
   "type": "graph",
   "description": "Rate of failed requests per second, split by error type (user/system)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_error_ns\" and r.namespace =~ /^${namespace:pipe}$/)\n|> range(start: start_dt, stop: end_dt)\n  |> keep(columns:[\"_time\", \"_field\", \"_value\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Requests drill down by nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Requests/s by Node",
     "type": "graph",
     "description": "Rate of successful requests per second, by node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n// how nice Flux can calculate left part of filter expressions!\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head_namespace\" and r._field == \"succeed_request_counter\" and (r.head + \":\" + r.namespace =~ /^${namespace:pipe}$/) )\n\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"namespace\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"namespace\"])\n|> sum()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})\n\n"
      }
     ]
    },
    {
     "title": "Failed Requests/s by Node",
     "type": "graph",
     "description": "Rate of failed requests per second, split by node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head_namespace\" and r._field == \"failed_request_counter\" and (r.head + \":\" + r.namespace =~ /^${namespace:pipe}$/) )\n\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"namespace\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"namespace\"])\n|> sum()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Compare: select multiple namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compare TPS of successful requests",
     "type": "graph",
     "description": "Select multiple namespaces and compare rates of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n  \n  from(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_transaction_ns\" and r._field == \"succeed_request_counter\" and r.namespace =~ /^${namespace:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_value\", \"namespace\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\", \"namespace\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
      }
     ]
    },
    {
     "title": "Compare TPS of failed requests",
     "type": "graph",
     "description": "Select multiple namespaces and compare rates of failed requests per second, split by error type (user/system)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n  \nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == \"cq_performance_error_ns\" and r.namespace =~ /^${namespace:pipe}$/)\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"namespace\"])  \n  |> window(every:wl_dur)\n  |> sum()\n  |> group(columns:[\"_field\",\"namespace\"]) \n  |> rename(columns: {_start: \"_time\"})"
      }
     ]
    }
   ]
  }
 ]
}