{
 "title": "Data Access Performance - by Nodes",
 "tags": [ "Data Access Performance" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Node",
    "query": "from(bucket:\"monitoring_main\")     |> range(start: -60m)     |> filter(fn:(r) => r._measurement == \"statDataHead_performance_internal_transactions\" )     |> group(columns:[\"host\"])     |> distinct(column:\"host\")"
   },
   { "name": "all_hosts", "label": "Show all nodes (experimental)", "query": "no,yes" }
  ]
 },
 "panels": [
  {
   "title": "Transaction Summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// need this 'default' table to substitute possibly missing sys_errors table if errors were not registered by ECS service\nimport \"csv\"\ndefault_sys_errors = csv.from(csv:\"#datatype,string,long,string,long\n#group,false,false,true,false\n#default,_result,,,\n,result,table,_field,_value\n,,100,succeed_request_counter,0\n,,101,system_errors,0\n,,102,user_errors,0\")\n\ntotals = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])\n|> difference(nonNegative: true)\n|> fill(column: \"_value\", value: 0)\n|> drop(columns:[\"host\"])\n|> sum()\n\nsys_errors = from(bucket: \"monitoring_main\")\n|> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_error\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])\n|> difference(nonNegative: true)\n|> drop(columns:[\"host\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nunion(tables: [default_sys_errors, totals, sys_errors])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")\n// map does not save non-group columns\n|> map(fn:(r) => ({\na_succeed_request_counter: r.succeed_request_counter,\nb_system_errors: r.system_errors,\nc_user_errors: r.user_errors,\nd_error_rate: float(v:r.system_errors+r.user_errors)/\nfloat(v:r.system_errors+r.user_errors+r.succeed_request_counter\n// this trick is needed because failed+succeed can be 0, avoid printing NaN in this case\n+int(v:bool(v:(r.system_errors+r.user_errors+r.succeed_request_counter)==0)))}))\n\n"
    }
   ]
  },
  {
   "title": "TPS (success/failure)",
   "type": "graph",
   "description": "Rate of successful requests and failures per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions\" and r._field =~ /_request_counter$/ and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> drop(columns:[\"host\"]) \n  |> sum() \n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Bandwidth (read/write)",
   "type": "graph",
   "description": "Data access bandwidth of successful requests per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_throughput\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> drop(columns:[\"host\"]) \n  |> sum() \n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})\n"
    }
   ]
  },
  {
   "title": "Failed Requests/s by error type (user/system)",
   "type": "graph",
   "description": "Rate of failed requests per second, split by error type (user/system)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_error\" and r._field =~ /_errors$/ and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> drop(columns:[\"host\"]) \n  |> sum() \n  |> group(columns:[\"_field\"]) \n  |> rename(columns: {_start: \"_time\"})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency of read/write requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\na = from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_latency\" and r._field =~ /.*/ and r.id == \"ttfb_read\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )  \n    |> range(start: start_dt, stop: end_dt)     \n    |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> fill(column: \"_value\", value: 0)\n    |> group(columns: [\"_field\"]) \n    |> window(every:wl_dur)     \n    |> sum()\n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Read, time to first byte, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Read, time to first byte, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\"])\n\n"
    },
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\na = from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_latency\" and r._field =~ /.*/ and r.id == \"ttlb_write\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )  \n    |> range(start: start_dt, stop: end_dt)     \n    |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> fill(column: \"_value\", value: 0)\n    |> group(columns: [\"_field\"]) \n    |> window(every:wl_dur)     \n    |> sum()\n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Write, time to last byte, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Write, time to last byte, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\"])\n\n"
    }
   ]
  },
  {
   "title": "Successful requests drill down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Requests/s by Method",
     "type": "graph",
     "description": "Rate of successful requests per second, by method",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_method\" and r._field == \"succeed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"method\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"host\"]) \n|> sum() \n|> group(columns:[\"method\"])\n|> rename(columns: {_start: \"_time\"})\n"
      }
     ]
    },
    {
     "title": "Successful Requests/s by Node",
     "type": "graph",
     "description": "Rate of successful requests per second, by node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions\" and r._field == \"succeed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})\n\n"
      }
     ]
    },
    {
     "title": "Successful Requests/s by Protocol",
     "type": "graph",
     "description": "Rate of successful requests per second, by Protocol",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head\" and r._field == \"succeed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)\n  |> keep(columns:[\"_time\", \"head\", \"_value\", \"host\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"host\"]) \n|> sum() \n|> group(columns:[\"head\"]) \n|> rename(columns: {_start: \"_time\", head: \"protocol\"})\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Failures drill down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Requests/s by Method",
     "type": "graph",
     "description": "Rate of failed requests per second, split by method",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_method\" and r._field == \"failed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n  |> range(start: start_dt, stop: end_dt)  \n|> keep(columns:[\"_time\", \"_value\", \"host\", \"method\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"host\"]) \n|> sum() \n|> group(columns:[\"method\"])\n|> rename(columns: {_start: \"_time\"})\n"
      }
     ]
    },
    {
     "title": "Failed Requests/s by Node",
     "type": "graph",
     "description": "Rate of failed requests per second, split by node",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions\" and r._field == \"failed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n|> range(start: start_dt, stop: end_dt) \n|> keep(columns:[\"_time\", \"_value\", \"host\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> group(columns:[\"_field\", \"host\"]) \n|> rename(columns: {_start: \"_time\", host: \"node\"})"
      }
     ]
    },
    {
     "title": "Failed Requests/s by Protocol",
     "type": "graph",
     "description": "Rate of failed requests per second, split by Protocol",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions_head\" and r._field == \"failed_request_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n  |> range(start: start_dt, stop: end_dt)\n  |> keep(columns:[\"_time\", \"head\", \"_value\", \"host\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"host\"]) \n|> sum() \n|> group(columns:[\"head\"]) \n|> rename(columns: {_start: \"_time\", head: \"protocol\"})\n"
      }
     ]
    },
    {
     "title": "Failed Requests/s by error code",
     "type": "graph",
     "description": "Rate of failed requests per second, split by error code",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_error_code\"  and r._field == \"error_counter\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n  |> range(start: start_dt, stop: end_dt)\n|> keep(columns:[\"_time\", \"_value\", \"host\", \"code\"]) \n|> derivative(nonNegative: true)\n// see MONITORING-194 for details about next 2 lines\n|> window(every:wl_dur)\n|> mean()\n|> drop(columns:[\"host\"]) \n|> sum() \n|> group(columns:[\"code\"])\n|> rename(columns: {_start: \"_time\"})\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Compare: select multiple nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compare TPS of success requests",
     "type": "graph",
     "description": "Select multiple nodes and compare rates of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_transactions\" and r._field =~ /succeed_request_counter$/ and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> group(columns:[\"_field\", \"host\"]) \n  |> rename(columns: {_start: \"_time\", host: \"node\"})\n"
      }
     ]
    },
    {
     "title": "Compare rate of failed requests/s",
     "type": "graph",
     "description": "Select multiple nodes and compare rates of failed requests per second, split by error type (user/system)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_error\" and r._field =~ /_errors$/ and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> group(columns:[\"_field\", \"host\"]) \n  |> rename(columns: {_start: \"_time\", host: \"node\"})"
      }
     ]
    },
    {
     "title": "Compare read bandwidth",
     "type": "graph",
     "description": "Select multiple nodes and compare data access bandwidth of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_throughput\" and r._field == \"total_read_requests_size\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> group(columns:[\"_field\", \"host\"]) \n  |> rename(columns: {_start: \"_time\", host: \"node\"})\n"
      }
     ]
    },
    {
     "title": "Compare write bandwidth",
     "type": "graph",
     "description": "Select multiple nodes and compare data access bandwidth of successful requests per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\nfrom(bucket: \"monitoring_main\") |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_throughput\" and r._field == \"total_write_requests_size\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )\n  |> range(start: start_dt, stop: end_dt)  \n  |> keep(columns:[\"_time\", \"_field\", \"_value\", \"host\"])  \n  |> derivative(nonNegative: true)\n  // see MONITORING-194 for details about next 2 lines\n  |> window(every:wl_dur)\n  |> mean()\n  |> group(columns:[\"_field\", \"host\"]) \n  |> rename(columns: {_start: \"_time\", host: \"node\"})\n"
      }
     ]
    },
    {
     "title": "Compare read latency",
     "type": "graph",
     "description": "Select multiple nodes and compare latency of read requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\na = from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_latency\" and r.id == \"ttfb_read\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )  \n    |> range(start: start_dt, stop: end_dt)     \n    |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> fill(column: \"_value\", value: 0)\n    |> group(columns: [\"_field\", \"host\"]) \n    |> window(every:wl_dur)     \n    |> sum()\n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Read, time to first byte, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Read, time to first byte, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\", \"host\"])\n\n"
      }
     ]
    },
    {
     "title": "Compare write latency",
     "type": "graph",
     "description": "Select multiple nodes and compare latency of write requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\nmin_window = 300\nmax_windows = 200\nsec_in_ns = 1000000000\nwindow_len = time_int / max_windows / min_window * min_window\nis_min_window = window_len < min_window\nwindow_len = (int(v:(is_min_window)) * min_window) + (int(v:(not is_min_window)) * window_len)\nwl_dur = duration(v:window_len * sec_in_ns)\nstart_dt = time(v:((int(v:$__range_from_s)/window_len) - 2) * window_len * sec_in_ns)\nend_dt = time(v:((int(v:$__range_to_s)/window_len) + 1) * window_len * sec_in_ns)\n\n\na = from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"statDataHead_performance_internal_latency\" and r.id == \"ttlb_write\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ) )  \n    |> range(start: start_dt, stop: end_dt)     \n    |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> fill(column: \"_value\", value: 0)\n    |> group(columns: [\"_field\", \"host\"]) \n    |> window(every:wl_dur)     \n    |> sum()\n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Write, time to last byte, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Write, time to last byte, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\", \"host\"])\n\n\n\n"
      }
     ]
    }
   ]
  }
 ]
}