{
 "title": "Garbage Collection: Capacity Reclaimed",
 "tags": [ "Garbage Collection" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Capacity Reclaimed",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "userReclaimed = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"user_gc_reclaimed\")\n|> range($range\r)\n|> last()\n|> keep(columns: [\"_time\", \"_value\"]) \n\nsystemReclaimed = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"system_gc_reclaimed\")\n|> range($range\r)\n|> last()\n|> keep(columns: [\"_time\", \"_value\"]) \n  \nunion(tables: [userReclaimed,systemReclaimed])\n|>sum()\n|> rename(columns:{_value: \"Capacity Reclaimed\"})"
    },
    {
     "query": "\nfrom(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"user_gc_reclaimed\")\n|> range($range\r)\n|> last()\n|> keep(columns: [\"_time\", \"_value\"]) \n|> rename(columns:{_value: \"User Data Reclaimed\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"system_gc_reclaimed\")\n|> range($range\r)\n|> last()\n|> keep(columns: [\"_time\", \"_value\"]) \n|> rename(columns:{_value: \"System Metadata Reclaimed\"})"
    }
   ]
  },
  {
   "title": "History Capacity Reclaimed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Data Reclaimed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "query": "extended_range_start = int(v:$__range_from_s) - 7200\nsafe_range_start = int(v:$__range_from_s) - 3600\nfrom(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"user_gc_reclaimed\")\n|> range(start: extended_range_start,stop:int(v:$__range_to_s)\r)\n|> difference(nonNegative: true)\n|> fill(column: \"_value\", value: 0)\n|> range(start: safe_range_start,stop:int(v:$__range_to_s)\r)"
      }
     ]
    },
    {
     "title": "System Metadata Reclaimed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "query": "extended_range_start = int(v:$__range_from_s) - 7200\nsafe_range_start = int(v:$__range_from_s) - 3600\nfrom(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_gc_data\" and r._field == \"system_gc_reclaimed\")\n|> range(start: extended_range_start,stop:int(v:$__range_to_s)\r)\n|> difference(nonNegative: true)\n|> fill(column: \"_value\", value: 0)\n|> range(start: safe_range_start,stop:int(v:$__range_to_s)\r)\n"
      }
     ]
    }
   ]
  }
 ]
}