{
 "title": "ObjectStore Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "// need this 'default' table to substitute possibly missing sys_errors table if errors were not registered by ECS service\nimport \"csv\"\ndefault_sys_errors = csv.from(csv:\"#datatype,string,long,string,long\n#group,false,false,true,false\n#default,_result,,,\n,result,table,_field,_value\n,,100,succeed_request_counter_i,0\n,,101,system_errors_i,0\n,,102,user_errors_i,0\")\n\ntotals = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_transaction_delta\")\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nsys_errors = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_performance_error_delta\")\n|> range($range)\n|> keep(columns:[\"_time\", \"_field\", \"_value\"])\n|> sum()\n|> fill(column: \"_value\", value: 0)\n\nunion(tables: [default_sys_errors, totals, sys_errors])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")\n// map does not save non-group columns\n|> map(fn:(r) => ({\n\"Successful Requests\": r.succeed_request_counter_i,\nb_system_errors: r.system_errors_i,\nc_user_errors: r.user_errors_i,\nd_error_rate: float(v:r.system_errors_i+r.user_errors_i)/\nfloat(v:r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i\n// this trick is needed because failed+succeed can be 0, avoid printing NaN in this case\n+int(v:bool(v:(r.system_errors_i+r.user_errors_i+r.succeed_request_counter_i)==0)))}))\n\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency of read/write requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "import \"ecs\"\n\nwi = ecs.get_dyn_downsample_info(start: $__range_from_s, stop: $__range_to_s, max: 200\n                                 measurement: \"cq_performance_latency\")\nmn = wi.measurement\n\nall = from(bucket: \"monitoring_vdc\") \n    |> filter(fn: (r) => r._measurement == mn )  \n    |> range(start: wi.start, stop: wi.stop)  \n    |> window(every: wi.duration)\n    |> mean()\n    |> group(columns:[\"_field\",\"id\"])\n\n// can't simple rename ttfb_read to Read, ti... and similarly for ttlb_write\n// when they are in same stream\n// TODO think about possible optimizations:\n// 1. use function? didn't work at first approach, flux can't see it\n// 2. use join with another table created from CSV\n\nreads = all |> filter(fn: (r) => r.id == \"ttfb_read\" )\n    |> set(key: \"id\", value: \"Read, time to first byte\")\n\nwrites = all |> filter(fn: (r) => r.id == \"ttlb_write\" )\n    |> set(key: \"id\", value: \"Write, time to last byte\")\n\nunion(tables: [reads, writes])|> map(fn:(r) => ({_time: r._start, _value: r._value, _field: r.id + \", \" + r._field })) |>drop(columns:[\"id\"])\n\n\n    \n\n\n"
    }
   ]
  },
  {
   "title": "Bandwidth (read/write)",
   "type": "graph",
   "description": "Data access bandwidth of successful requests per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "query": "import \"ecs\"\n\nwi = ecs.get_dyn_downsample_info(start: $__range_from_s, stop: $__range_to_s, max: 200\n                                 measurement: \"cq_performance_throughput\")\nmn = wi.measurement\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == mn and r._field == \"total_read_requests_size\" )\n|> range(start: wi.start, stop: wi.stop) \n|> keep(columns:[\"_time\", \"_field\", \"_value\"]) \n|> window(every: wi.duration)\n|> mean()\n|> group(columns:[\"_field\"]) \n|> rename(columns: {_start: \"_time\"})\n|> set(key: \"_field\", value: \"Read Bandwidth\")\n\n"
    },
    {
     "query": "import \"ecs\"\n\nwi = ecs.get_dyn_downsample_info(start: $__range_from_s, stop: $__range_to_s, max: 200\n                                 measurement: \"cq_performance_throughput\")\nmn = wi.measurement\n\nfrom(bucket: \"monitoring_vdc\") |> filter(fn: (r) => r._measurement == mn and r._field == \"total_write_requests_size\" )\n|> range(start: wi.start, stop: wi.stop) \n|> keep(columns:[\"_time\", \"_field\", \"_value\"]) \n|> window(every: wi.duration)\n|> mean()\n|> group(columns:[\"_field\"]) \n|> rename(columns: {_start: \"_time\"})\n|> set(key: \"_field\", value: \"Write Bandwidth\")"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\" and r._field == \"total_i\")\n|> range($range)\r\n|> last()\r"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\" and r._field == \"used\")\n|> range($range)\r\n|> last()\r"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "// see MONITORING-410 for more details\n\n// COLLECT DATA FROM PRECALCULATED VDC VALUES\nfrom(bucket: \"monitoring_vdc\")\n  |> filter(fn: (r) => r._measurement == \"cq_gc_data\"\n                       or r._measurement == \"cq_capacity_used_elements\"\n  )\n  |> range($range)\n  |> last()\n  // remove difference with measurement name\n  |> set(key: \"_measurement\", value: \"1\")\n  // group will make all tag columns removed in map()\n  |> group()\n  |> pivot(rowKey:[\"_measurement\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n \n  |> map(fn: (r) => ({\n \"vl0_User Data\": r.user_data - r.user_gc_pending - r.user_gc_unreclaim,\n \"vl1_System Metadata\": r.meta_data - r.system_gc_pending - r.system_gc_unreclaim,\n \"vl2_Protection Overhead\": r.protection_overhead_wo_geo,\n \"vl5_Garbage\":  r.user_gc_pending + r.user_gc_unreclaim\n               + r.system_gc_pending + r.system_gc_unreclaim\n }))\n"
    }
   ]
  },
  {
   "title": "Storage Efficiency",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_ec\"\r and r._field == \"total_coding_data\")\r\n|> range($range)\r\n|> last()\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_ec\"\r and r._field == \"total_coded_data\")\r\n|> range($range)\r\n|> last()\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_ec\"\r and (r._field == \"total_coding_data\" or r._field == \"total_coded_data\"))\r\n|> range($range)\r\n|> last()\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({coded_ratio: r.total_coded_data / r.total_coding_data}))\n"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_ec\"\r and r._field == \"coding_rate\")\r\n|> range($range)\r\n|> last()\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_capacity_ec\"\r and (r._field == \"total_coding_data\" or r._field == \"total_coded_data\" or r._field == \"coding_rate\"))\r\n|> range($range)\r\n|> last()\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({est_time: (r.total_coding_data - r.total_coded_data) / (r.coding_rate)}))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "nodeStatus = from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_ss_state\" and r._field == \"SSState\")\r\n|> range($range)\r\n|> last()\r\n|> keep(columns: [\"SS\", \"_value\"])\r\n\r\nnodeStatusGood = nodeStatus |> filter(fn: (r) => r._value == 1) |> keep(columns: [\"_value\"])\r\n|> count()\r\n|> set(key: \"_field\", value: \"Good Nodes\")\r\n\nnodeStatusBad = nodeStatus |> filter(fn: (r) => r._value != 1) |> keep(columns: [\"_value\"])\n|> count()\r\n|> set(key: \"_field\", value: \"Bad Nodes\")\r\n\nunion(tables: [nodeStatusGood , nodeStatusBad ])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Data Disks",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "\r\ndisks = from(bucket: \"monitoring_vdc\")\r\n|> filter(fn: (r) => r._measurement == \"cq_disk_state\" and r._field == \"hwState\")\r\n|> range($range)\r\n|> last()\r\n|> keep(columns: [\"_value\"])\n\r\n//filter out different statuses\r\ngood_d = disks\r\n|> filter(fn: (r) => r._value == \"GOOD\")\n|> count()\r\n|> set(key: \"_field\", value: \"Good Disks\")\r\n\r\nbad_d = disks\r\n|> filter(fn: (r) => r._value == \"BAD\" or r._value == \"SUSPECT\")\n|> count()\r\n|> set(key: \"_field\", value: \"Bad Disks\")\r\n\r\nmaintenance_d = disks\r\n|> filter(fn: (r) => r._value == \"MAINTENANCE\")\n|> count()\r\n|> set(key: \"_field\", value: \"Maintenance Disks\")\r\n\r\nunion(tables: [good_d , bad_d , maintenance_d ])\n|> pivot(rowKey:[], columnKey: [\"_field\"], valueColumn: \"_value\")\n"
    }
   ]
  }
 ]
}