{
 "title": "Recovery Status",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Recovery Status",
   "type": "table",
   "description": "The table displays the latest values of the logical size of the data yet to be recovered, the rate at which data is being recovered and time to recovery completion in the selected time range.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "a = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_recover_status_summary\" and r._field == \"data_to_recover\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\"])\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"data\"})\n|> yield(name: \"1\")\n\noffset = 21600\r\nextended_range_start = int(v:$__range_to_s) - offset\r\nextended_range_stop = int(v:$__range_to_s)\nb = from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_recover_status_summary\" and r._field == \"data_recovered\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> window(every: 15m)\n|> last()\n|> keep(columns: [\"_time\", \"_value\"])\n|> derivative(nonNegative: true, columns: [\"_value\"])\n|> mean()\n|> rename(columns: {_value: \"rate\"})\n|> yield(name: \"2\")\n\njoin(tables: {aa: a, bb: b})\n|> map(fn: (r) => ({\"ETC\": \n                    if (r.data > 0 and r.rate > 0) then string(v:float(v:r.data)/r.rate) else \"-\",\n                    \"range\": \"$range\"}))\n|> map(fn: (r) => ({ETC: if ((r.range =~ /stop/)) then \"-\" else r.ETC})"
    }
   ]
  },
  {
   "title": "Amount of Data to be Recovered",
   "type": "graph",
   "description": "History of the amount of data pending recovery in the selected time range.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_recover_status_summary\" and r._field == \"data_to_recover\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\"])\n|> set(key: \"_field\", value: \"Amount of Data to be Recovered\")"
    }
   ]
  },
  {
   "title": "Recovery Rate (per second)",
   "type": "graph",
   "description": "History of the rate at which data was recovered.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "offset = 300\r\nextended_range_start = int(v:$__range_from_s) - offset\r\nextended_range_stop = int(v:$__range_to_s)\nfrom(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_recover_status_summary\" and r._field == \"data_recovered\")\n|> range(start: extended_range_start, stop: extended_range_stop)\n|> keep(columns: [\"_time\", \"_value\"])\n|> derivative(nonNegative: true, columns: [\"_value\"])\n|> range($range)\n|> set(key: \"_field\", value: \"Recovery Rate\")"
    }
   ]
  }
 ]
}