{
 "title": "SSD Read Cache",
 "tags": [ "SSD Read Cache" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Node",
    "query": "from(bucket:\"monitoring_main\")     |> range(start: -60m)     |> filter(fn:(r) => r._measurement == \"blob_SSDReadCache_Stats\" )     |> group(columns:[\"host\"])     |> distinct(column:\"host\")"
   }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "query": "import \"ecs\"\n\nwi = ecs.get_dynamic_window_info(int_start: $__range_from_s, int_stop: $__range_to_s, max: 200)\n\na = from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"blob_SSDReadCache_Stats\" and r.id == \"get_latency_counter\"  and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))  \n    |> range(start: wi.start, stop: wi.stop)         \n|> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> group(columns: [\"_field\"]) \n    |> window(every: wi.duration)     \n    |> sum() |> fill(column: \"_value\", value: 0) \n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Get latency, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Get latency, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\"])"
    },
    {
     "query": "import \"ecs\"\n\nwi = ecs.get_dynamic_window_info(int_start: $__range_from_s, int_stop: $__range_to_s, max: 200)\n\na= from(bucket: \"monitoring_main\") \n    |> filter(fn: (r) => r._measurement == \"blob_SSDReadCache_Stats\" and r.id == \"put_latency_counter\"  and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))  \n    |> range(start: wi.start, stop: wi.stop)     \n    |> drop(columns:[\"_measurement\", \"process\", \"tag\"])\n    |> difference(nonNegative: true) \n    |> group(columns: [\"_field\"]) \n    |> window(every: wi.duration)     \n    |> sum() |> fill(column: \"_value\", value: 0) \n    |> map(fn:(r) => ({_time:r._start, le_float: float(v:r._field), cnt_float: float(v:r._value)}))\n    |> drop(columns:[\"_field\", \"_stop\"]) \n    \np50 = a |> histogramQuantile(quantile:0.50, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Put latency, p50\")\np99 = a |> histogramQuantile(quantile:0.99, upperBoundColumn: \"le_float\", countColumn: \"cnt_float\")\n|> rename(columns:{_start: \"_time\"})\n|> set(key: \"_field\", value: \"Put latency, p99\")\nunion(tables: [p50, p99])|> group(columns:[\"_field\"])\n"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_main\") \r\n    |> filter(fn: (r) => r._measurement == \"blob_SSDReadCache_Stats\" and r._field == \"rocksdb_disk_usage_counter_bytes\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ ))\r\n    \r|> range($range)\r\n    |> keep(columns:[\"_time\", \"_field\", \"_value\"])\r\n    |> map(fn: (r) => ({_time: r._time, _field: \"Used bytes\", _value: r._value}))\r\n"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_main\") \r\n    |> filter(fn: (r) => r._measurement == \"blob_SSDReadCache_Stats\" and r._field == \"ssd_capacity_counter_bytes\" and (\"${all_hosts}\" == \"yes\" or r.host =~ /^${host:pipe}$/ )\r)\n    \r|> range($range)\r\n    |> keep(columns:[\"_time\", \"_field\", \"_value\"])\r\n    |> map(fn: (r) => ({_time: r._time, _field: \"Disk Capacity\", _value: r._value}))\r\n"
    }
   ]
  }
 ]
}