{
 "title": "Process Health - Overview",
 "tags": [ "Process Health" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Process Health Overview by Cluster",
   "type": "table",
   "description": "Monitor the Cluster use of network interface, CPU, and available memory.\nThe table displays the latest average values and the history graphs display values in the selected time range.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"cpu_used\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns: {_value: \"Avg. CPU Usage\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"mem_used\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"Avg. Memory Usage\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"mem_used_percent\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"Avg. Relative Memory (%)\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"nic_bytes\")\n|> range($range)\n|> derivative(unit: 1s, nonNegative: true)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value: \"Avg. NIC Bandwidth\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"nic_utilization\")\n|> range($range)\n|> derivative(unit: 1s, nonNegative: true)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value: \"Relative NIC (%)\"})"
    }
   ]
  },
  {
   "title": "History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. CPU Usage",
     "type": "graph",
     "description": "History of the average percentage of the CPU hardware used by the Cluster in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"cpu_used\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"Avg. CPU Usage\")"
      }
     ]
    },
    {
     "title": "Avg. NIC Bandwidth",
     "type": "graph",
     "description": "History of the average bandwidth of the network interface controller hardware used by the Cluster in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"nic_bytes\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> derivative(unit: 1s, nonNegative: true)\n|> set(key: \"_field\", value: \"Avg. NIC Bandwidth\")"
      }
     ]
    },
    {
     "title": "Avg. Memory Usage",
     "type": "graph",
     "description": "History of average usage of the aggregate memory available to the Cluster in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"mem_used\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"Avg. Memory Usage\")"
      }
     ]
    },
    {
     "title": "Avg. Relative Memory (%)",
     "type": "graph",
     "description": "History of the percentage of the memory used relative to the memory available to the Cluster in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_process_health\" and r._field == \"mem_used_percent\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"Avg. Relative Memory (%)\")"
      }
     ]
    }
   ]
  }
 ]
}