{
 "title": "Node system metrics",
 "description": "(\"server single\")",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(monitoring_op, cpu, host)"
   },
   { "name": "reduced_data_rate", "label": "auto resolution", "query": "on,off" },
   {
    "name": "disk_latency_host",
    "query": "tag_values(monitoring_op, cpu, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"free\" and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"swap\" and r._field == \"used_percent\" and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Free System Disk Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "space" }
   ],
   "targets": [
    {
     "alias": "space: free, $tag_path",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"fs_available_bytes\" and r.node_name =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"node_name\"])\n|> rename(columns:{node_name:\"host\"})\n",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"linux_sysctl_fs\" and (r._field == \"file-nr\" or r._field == \"file-max\") and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"host\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "CPU, Load, Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent", "label": "usage" }
     ],
     "targets": [
      {
       "alias": "usage_system",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"cpu\" and r.cpu == \"cpu-total\" and r._field == \"usage_idle\" and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> map(fn: (r) => ({_value: 100.0 - r._value, _time: r._time}))\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "system: load (5m)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "load (5m)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"system\" and r._field == \"load5\" and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])\n",
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total threads count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "time_int = int(v:$__range_to_s) - int(v:$__range_from_s)\npoints_period = 300\r\nmax_points = 90 \nsample_n = time_int / max_points / points_period\ndisable_reduced_data_rate = (\"$reduced_data_rate\" == \"off\") or (sample_n < 1)\r\nprecalc = int(v:(not disable_reduced_data_rate)) * sample_n\nsample_n = int(v:disable_reduced_data_rate) + precalc\r\n\nsec_in_ns = 1000000000\r\nsampled_period = sample_n * points_period\r\nstart_dt = time(v:((int(v:$__range_from_s)/sampled_period) - 2) * sampled_period * sec_in_ns)\r\nend_dt = time(v:((int(v:$__range_to_s)/sampled_period) + 1) * sampled_period * sec_in_ns)\r\n\nfrom(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"processes\" and r._field == \"total_threads\" and r.host =~ /${host:pipe}/)\n|> range(start: start_dt, stop: end_dt)\n|> sample(n: sample_n, pos: 0)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IP Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "IP traffic (outbound)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Out (5m)",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "from(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"nstat\" and r._field == \"IpExtOutOctets\" and r.host =~ /${host:pipe}/)\n|> range($range)\n|> derivative(unit: 1s, nonNegative: true)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "IpExtOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "IP traffic (inbound)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Out (5m)",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "from(bucket: \"monitoring_op\")\r\n  |> filter(fn: (r) => r._measurement == \"nstat\" and r._field == \"IpExtInOctets\" and r.host =~ /${host:pipe}/)\n  |> range($range)\n  |> derivative(unit: 1s, nonNegative: true)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "IpExtOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP errors (input segments)",
     "type": "graph",
     "description": "Rate (per second) of total number of segments that are received in error (for example, bad TCP checksums).",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Out (5m)",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "from(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"nstat\" and r._field == \"TcpInErrs\" and r.host =~ /${host:pipe}/)\n|> range($range)\n|> derivative(unit: 1s, nonNegative: true)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "IpExtOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "UDP errors (input datagrams)",
     "type": "graph",
     "description": "Rate (per second) of total number of received UDP datagrams that could not be delivered for reasons other than the lack of an application at the destination port.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Out (5m)",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nstat",
       "query": "from(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"nstat\" and r._field == \"UdpInErrors\" and r.host =~ /${host:pipe}/)\n|> range($range)\n|> derivative(unit: 1s, nonNegative: true)\n|> keep(columns: [\"_time\", \"_value\", \"host\"])",
       "select": [
        [
         { "params": [ "IpExtOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}