{
 "title": "Process Health - Process List by Pod",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod_regexp", "query": "<__enter_pod_name__>" },
   {
    "name": "namespace",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" )|> range(start: -1h)|> last()|> group(columns: [\"namespace\"])|> distinct(column: \"namespace\")"
   },
   {
    "name": "pod",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r.namespace == \"${namespace}\" and r.pod_name=~ /${pod_regexp:pipe}/  )|> range(start: -1h)|> last()|> group(columns: [\"pod_name\"])|> distinct(column: \"pod_name\")"
   },
   {
    "name": "host",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r.namespace == \"${namespace}\" and r.pod_name=~ /${pod:pipe}/  )|> range(start: -1h)|> last()|>limit(n:10)|> group(columns: [\"node_name\"])|> distinct(column: \"node_name\")"
   },
   {
    "name": "container",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r.namespace == \"${namespace}\" and r.pod_name=~ /${pod:pipe}/  )|> range(start: -1h)|> last()|>limit(n:10)|> group(columns: [\"container_name\"])|> distinct(column: \"container_name\")"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "History of the percentage of the node's CPU used by the process in the selected time range. The maximum time range could be the last 5 days because it is limited by the retention policy.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "per_node = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"cpu_usage_nanocores\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\"])\n\ncpu_cores = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"system\" and r._field == \"n_cpus\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> rename(columns: {_value:\"cpu_total\"})\n\njoin(tables: {cpu: per_node, cores: cpu_cores}, on:[\"_time\"])\n|> map(fn: (r) => ({_value: (float(v:r._value) / 1000000000.0) / float(v:r.cpu_total), _time: r._time}))\n|> keep(columns: [\"container_name\", \"_value\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "History of the memory used by the process in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])"
    }
   ]
  },
  {
   "title": "Relative Memory (%)",
   "type": "graph",
   "description": "History of the percentage of the memory used relative to the memory available to the process in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "process_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])\n\nnode_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"total\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> rename(columns:{_value: \"total_mem\"})\n\njoin(tables: {sf: process_mem, ny: node_mem}, on: [\"_time\"])\n|> map(fn: (r) => ({_value: float(v:r._value)/float(v:r.total_mem) * 100.0, _time: r._time}))\n|> set(key: \"_field\", value: \"relative_mem\")\n"
    }
   ]
  },
  {
   "title": "Pod Network I/O",
   "type": "graph",
   "description": "Pod network statistics (sent / received bytes)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r._field == \"rx_bytes\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ )\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Received Bytes\")\n"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r._field == \"tx_bytes\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ )\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Sent Bytes\")"
    }
   ]
  },
  {
   "title": "Last Activity",
   "type": "table",
   "description": "The last time the process restarted on the node in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> last()\n|> rename(columns:{_time: \"Last Activity\"})"
    }
   ]
  }
 ]
}