{
 "title": "Capacity - Overview",
 "tags": [ "Capacity" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "release_name",
    "label": "Object Store",
    "query": "from(bucket:\"monitoring_vdc\")|> range(start: -24h)|> filter(fn:(r) => r._measurement == \"cq_capacity_vdc\")|> keep(columns: [\"release_name\"])|> group(columns:[\"release_name\"])|> distinct(column:\"release_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "table",
   "description": "Summary  by all Object Stores,  shows last values.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n  |> filter(fn: (r) => r._measurement == \"cq_capacity_region\"\n                       and (r._field == \"total_i\" or r._field == \"used\"\n                            or r._field == \"available\" or r._field == \"reserved\"\n                            or r._field == \"offline\"))\n  |> range($range)\n  |> last()\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n  |> map(fn: (r) => ({\"vl0_Total\": r.total_i, \"vl1_Used\": r.used, \"vl2_Available\": r.available, \"vl3_Reserved\": r.reserved}))\n"
    }
   ]
  },
  {
   "title": "Capacity History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "graph",
     "description": "Summary  by all Object Stores for Total available capacity",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_region\" and r._field == \"total_i\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Total\")"
      }
     ]
    },
    {
     "title": "Used",
     "type": "graph",
     "description": "Summary  by all Object Stores for total Used capacity",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_region\" and r._field == \"used\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Used\")\n"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "description": "Summary  by all Object Stores for total Available(free) capacity",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_region\" and r._field == \"available\")\n|> range($range)\n|> group()\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Available\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "ObjectStores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Info  by each Object Store separately,  shows last values.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n  |> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"\n                       and (r._field == \"total_i\" or r._field == \"used\"\n                            or r._field == \"available\" or r._field == \"reserved\"\n                            or r._field == \"offline\" or r._field == \"used\"))\n  |> range($range)\n  |> last()\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"release_name\"])\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"],valueColumn: \"_value\")\n  |> map(fn: (r) => ({\"vl1_Total\": r.total_i, \"vl2_Used\": r.used, \"vl3_Available\": r.available, \"vl4_Reserved\": r.reserved, \"vl5_Offline\":  r.offline}))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity History by ObjectStore ($release_name)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "graph",
     "description": "Info by selected Object Store in filter for Total available capacity",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"\nand r.release_name == \"$release_name\"\nand r._field == \"total_i\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"release_name\"])\n|> set(key: \"_field\", value: \"Total\")\n|> rename(columns: {release_name: \"ObjectStore\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "graph",
     "description": "Info by selected Object Store in filter for total Used capacity",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"\nand r.release_name == \"$release_name\"\nand r._field == \"used\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"release_name\"])\n|> set(key: \"_field\", value: \"Used\")\n|> rename(columns: {release_name: \"ObjectStore\"})"
      }
     ]
    },
    {
     "title": "Available",
     "type": "graph",
     "description": "Info by selected Object Store in filter for total Available(free) capacity",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_capacity_vdc\"\nand r.release_name == \"$release_name\"\nand r._field == \"available\")\n|> range($range)\n|> keep(columns: [\"_time\", \"_value\", \"_field\", \"release_name\"])\n|> set(key: \"_field\", value: \"Available\")\n|> rename(columns: {release_name: \"ObjectStore\"})"
      }
     ]
    }
   ]
  }
 ]
}