{
 "title": "Node Rebalancing",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Node Rebalancing Overview",
   "type": "table",
   "description": "The table displays the lastest values for the selected time range.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"data_rebalanced\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"Data Rebalanced\"})"
    },
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"pending_rebalance\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"Pending Rebalancing\"})"
    },
    {
     "query": "\nfrom(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"data_rebalanced\")\n|> range($range)\n|> derivative(unit:24h, nonNegative: true, columns: [\"_value\"])\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value:\"Rate of Rebalance (per day)\"})"
    }
   ]
  },
  {
   "title": "Data Rebalanced",
   "type": "graph",
   "description": "History of the amount of data that has been rebalanced.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"data_rebalanced\")\n|> range($range)\n|> drop(columns: [\"_measurement\"])\n|> set(key: \"_field\", value: \"Data Rebalanced\")"
    }
   ]
  },
  {
   "title": "Pending Rebalancing",
   "type": "graph",
   "description": "History of the amount of data that is in the rebalance queue but has not been rebalanced yet.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"pending_rebalance\")\n|> range($range)\n|> drop(columns: [\"_measurement\"])\n|> set(key: \"_field\", value: \"Pending Rebalancing\")"
    }
   ]
  },
  {
   "title": "Rate of Rebalance (per day)",
   "type": "graph",
   "description": "History of the incremental amount of data that was rebalanced for 24 hours.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"monitoring_vdc\")\n|> filter(fn: (r) => r._measurement == \"cq_rebalancing_region\" and r._field == \"data_rebalanced\")\n|> range($range)\n|> drop(columns: [\"_measurement\"])\n|> derivative(unit:24h, nonNegative: true, columns: [\"_value\"])\n|> range($range)\n|> set(key: \"_field\", value: \"Rate\")"
    }
   ]
  }
 ]
}