{
 "title": "Process Health - by Nodes",
 "tags": [ "Process Health" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(monitoring_op, cpu, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process Health by Nodes",
   "type": "table",
   "description": "Monitor for each node of the Cluster use of network interface, CPU, and available memory. The table displays the latest values and the history graphs display values in the selected range.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"monitoring_op\")\n|> range(start: -1h)\n|> filter(fn:(r) => r._measurement == \"cpu\")\n|> group(columns:[\"host\"])\n|> distinct(column:\"host\")\n|> keep(columns: [\"host\"])"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used\")\n|> range($range)\n|> last()\n|> keep(columns: [\"host\", \"_value\"])\n|> rename(columns:{_value:\"Memory Usage\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\", \"host\"])\n|> rename(columns:{_value:\"Relative Memory (%)\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_user\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\", \"host\"])\n|> rename(columns:{_value:\"CPU Usage\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and (r._field == \"network_rx_bytes\" or r._field == \"network_tx_bytes\"))\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"_field\", \"node_name\"])\n|> derivative(nonNegative: true, unit:1s)\n|> last()\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({_time: r._time, _value: r.network_rx_bytes + r.network_tx_bytes}))\n|> rename(columns:{_value:\"NIC Bandwidth\", node_name: \"host\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\r\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"fs_available_bytes\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\", \"node_name\"])\n|> rename(columns:{_value:\"Free FS Space\", node_name: \"host\"})\n"
    }
   ]
  },
  {
   "title": "History ${host}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "History of the average percentage of the CPU hardware used by the selected node in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_user\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"CPU Usage\")"
      }
     ]
    },
    {
     "title": "NIC Bandwidth",
     "type": "graph",
     "description": "History of the average bandwidth of the network interface controller hardware used by the selected node in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"network_rx_bytes\" and r.node_name == \"$host\")\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"_field\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Receive Rate\")"
      },
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"network_tx_bytes\" and r.node_name == \"$host\")\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"_field\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Send Rate\")\n"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "History of average usage of the aggregate memory available to the selected node in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"Memory Used\")"
      }
     ]
    },
    {
     "title": "Relative Memory (%)",
     "type": "graph",
     "description": "History of the percentage of the memory used relative to the memory available to the selected node in the selected time range.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> set(key: \"_field\", value: \"Memory Used %\")"
      }
     ]
    },
    {
     "title": "File System Usage",
     "type": "graph",
     "description": "File system usage on the node (percent of total available space).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"fs_used_bytes\" and r.node_name == \"$host\")\n|> range($range)\n|> keep(columns:[\"_stop\", \"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Used Space\")\n"
      },
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and r._field == \"fs_capacity_bytes\" and r.node_name == \"$host\")\n|> range($range)\n|> keep(columns:[\"_stop\", \"_time\", \"_value\", \"_field\"])\n|> set(key: \"_field\", value: \"Total Space\")"
      }
     ]
    },
    {
     "title": "File System Usage (%)",
     "type": "graph",
     "description": "File system usage on the node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_node\" and (r._field == \"fs_used_bytes\" or r._field == \"fs_capacity_bytes\") and r.node_name == \"$host\")\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"_field\"])\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> map(fn: (r) => ({_time: r._time, _value: float(v:r.fs_used_bytes) / float(v:r.fs_capacity_bytes)}))\n|> set(key: \"_field\", value: \"FS Used %\")\n"
      }
     ]
    }
   ]
  }
 ]
}