{
 "title": "Process Health - Process List by Node",
 "tags": [ "Process Health" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "tag_values(monitoring_op, kubernetes_node, host)"
   },
   {
    "name": "namespace",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r.node_name == \"${host}\")|> range(start: -1h)|> last()|> group(columns: [\"namespace\"])|> distinct(column: \"namespace\")"
   },
   {
    "name": "pod",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r.node_name == \"${host}\" and r.namespace == \"${namespace}\")|> range(start: -1h)|> last()|> group(columns: [\"pod_name\"])|> distinct(column: \"pod_name\")"
   },
   {
    "name": "container",
    "query": "from(bucket: \"monitoring_op\")|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r.node_name == \"${host}\" and r.namespace == \"${namespace}\" and r.pod_name=~ /${pod:pipe}/  )|> range(start: -1h)|> last()|> group(columns: [\"container_name\"])|> distinct(column: \"container_name\")"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview of The Pods List on ${host}",
   "type": "table",
   "description": "Monitor processes use of CPU, memory, average thread number and last restart time in the selected time range. The table displays the latest values in the selected time range. ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "per_node = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"cpu_usage_nanocores\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\")\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\"])\n|> last()\n|> drop(columns: [\"container_name\"])\n|> sum()\n|> group(columns:[\"pod_name\"])\n\ncpu_cores = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"system\" and r._field == \"n_cpus\" and r.host == \"${host}\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\", \"_time\"])\n|> drop(columns: [\"_time\"])\n|> rename(columns: {_value:\"cpu_total\"})\n\njoin(tables: {cpu: per_node, cores: cpu_cores})\n|> map(fn: (r) => ({_value: (float(v:r._value) / 1000000000.0 ) / float(v:r.cpu_total)}))\n|> keep(columns: [\"_value\", \"pod_name\"])\n|> rename(columns:{_value: \"CPU Usage\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\")\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\"])\n|> last()\n|> drop(columns: [\"container_name\"])\n|> sum()\n|> group(columns:[\"pod_name\"])\n|> rename(columns:{_value: \"Memory\"})"
    },
    {
     "query": "pod_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\")\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\"])\n|> last()\n|> drop(columns: [\"container_name\"])\n|> sum()\n|> group(columns:[\"pod_name\"])\n\nnode_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"total\" and r.host == \"${host}\")\n|> range($range)\n|> last()\n|> keep(columns: [\"_value\"])\n|> rename(columns:{_value: \"total_mem\"})\n\njoin(tables: {sf: pod_mem, ny: node_mem})\n|> map(fn: (r) => ({_value: float(v:r._value)/float(v:r.total_mem) * 100.0}))\n|> keep(columns: [\"pod_name\", \"_value\"])\n|> rename(columns: {_value:\"Relative Memory (%)\"})"
    },
    {
     "query": "firstV=from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and (r._field == \"rx_bytes\" or r._field == \"tx_bytes\") and r.namespace == \"$namespace\" and r.node_name == \"$host\" )\n|> range($range)\n|> first()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"_field\"])\n\nlastV=from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and (r._field == \"rx_bytes\" or r._field == \"tx_bytes\") and r.namespace == \"$namespace\" and r.node_name == \"$host\" )\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"_field\"])\n\nunion(tables:[firstV,lastV])\n|> sort(columns: [\"_time\"])\n|> derivative(nonNegative: true, unit:1s)\n|> last()\n|> keep(columns:[\"_value\", \"pod_name\"])\n|> sum()\n|> rename(columns:{_value: \"Network IO\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"inventory_kubernetes_pod_container\" and r._field == \"state_code\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\")\n|> range($range)\n|> last()\n|> keep(columns:[\"_value\", \"pod_name\"])\n|> last()\n|> map(fn: (r) => ( {pod_name: r.pod_name,\nStatus: if r._value == 0 then \"Running\" else string(v:if r._value == 1 then \"Terminated\" else string(v:if r._value == 2 then \"Waiting\" else \"Unknown\"))}))"
    },
    {
     "query": "firstV=from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"inventory_kubernetes_pod_container\" and r._field == \"restarts_total\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" )\n|> range($range)\n|> first()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\", \"_field\"])\n\nlastV=from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"inventory_kubernetes_pod_container\" and r._field == \"restarts_total\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" )\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\", \"_field\"])\n\nunion(tables:[firstV,lastV])\n|> sort(columns: [\"_time\"])\n|> difference(columns: [\"_value\"])\n|> last()\n|> keep(columns:[\"_value\", \"pod_name\"])\n|> sum()\n|> rename(columns:{_value: \"Restarts\"})"
    },
    {
     "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\")\n|> range($range)\n|> last()\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\"])\n|> last()\n|> rename(columns:{_time: \"Last Activity\"})"
    }
   ]
  },
  {
   "title": "History \"${pod}\" process on ${host}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "process",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "History of the percentage of the node's CPU used by the process in the selected time range. The maximum time range could be the last 5 days because it is limited by the retention policy.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "per_node = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"cpu_usage_nanocores\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"pod_name\", \"container_name\"])\n\ncpu_cores = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"system\" and r._field == \"n_cpus\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> rename(columns: {_value:\"cpu_total\"})\n\njoin(tables: {cpu: per_node, cores: cpu_cores}, on:[\"_time\"])\n|> map(fn: (r) => ({_value: (float(v:r._value) / 1000000000.0) / float(v:r.cpu_total), _time: r._time}))\n|> keep(columns: [\"container_name\", \"_value\", \"_time\"])"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "History of the memory used by the process in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])"
      }
     ]
    },
    {
     "title": "Relative Memory (%)",
     "type": "graph",
     "description": "History of the percentage of the memory used relative to the memory available to the process in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "query": "process_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])\n\nnode_mem = from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"total\" and r.host == \"${host}\")\n|> range($range)\n|> keep(columns: [\"_value\", \"_time\"])\n|> rename(columns:{_value: \"total_mem\"})\n\njoin(tables: {sf: process_mem, ny: node_mem}, on: [\"_time\"])\n|> map(fn: (r) => ({_value: float(v:r._value)/float(v:r.total_mem) * 100.0, _time: r._time}))\n|> set(key: \"_field\", value: \"relative_mem\")\n"
      }
     ]
    },
    {
     "title": "Pod Network I/O",
     "type": "graph",
     "description": "Pod network statistics (sent / received bytes)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r._field == \"rx_bytes\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ )\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Received Bytes\")\n"
      },
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_network\" and r._field == \"tx_bytes\" and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ )\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> derivative(nonNegative: true, unit:1s)\n|> set(key: \"_field\", value: \"Sent Bytes\")"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "graph",
     "description": "Total number of restarts of container inside pod",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"inventory_kubernetes_pod_container\" and r._field == \"restarts_total\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])\n|> difference()\n"
      }
     ]
    },
    {
     "title": "Status",
     "type": "graph",
     "description": "Status of containers.\n0 - Running\n1 - Terminated\n2 - Waiting\n3 - Unknown",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"inventory_kubernetes_pod_container\" and r._field == \"state_code\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\", \"container_name\"])\n"
      }
     ]
    },
    {
     "title": "Last Activity",
     "type": "table",
     "description": "The last time the process restarted on the node in the selected time range. The maximum time range could be 5 days because it is limited by the retention policy.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "query": "from(bucket: \"monitoring_op\")\n|> filter(fn: (r) => r._measurement == \"kubernetes_pod_container\" and r._field == \"memory_rss_bytes\"  and r.namespace == \"$namespace\" and r.node_name == \"$host\" and r.pod_name =~ /${pod:pipe}/ and r.container_name =~ /${container:pipe}/)\n|> range($range)\n|> keep(columns:[\"_time\", \"_value\"])\n|> last()\n|> rename(columns:{_time: \"Last Activity\"})"
      }
     ]
    }
   ]
  }
 ]
}